name: Logic App Deployment

on:
  workflow_dispatch:
    inputs:

      branch:
        description: Branch Name
        required: true
        default: main-dev
        type: choice
        options:
          - main-dev
          - main

      environment:
        description: Environment
        required: true
        default: DEV
        type: choice
        options:
          - DEV
          - UAT
          - PROD

      logicapp:
        description: Logic App Name
        required: true
        default: order-processing
        type: choice
        options:
          - order-processing

jobs:

  deploy:

    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.environment }}

    concurrency:
      group: logicapp-${{ github.event.inputs.environment }}
      cancel-in-progress: false

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId":"${{ secrets.ARM_CLIENT_ID }}",
              "clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}",
              "subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}",
              "tenantId":"${{ secrets.ARM_TENANT_ID }}"
            }

      - name: Deploy Logic App

        run: |

          az deployment group create \
            --resource-group rg-order-${{ github.event.inputs.environment }} \
            --template-file logic-apps/${{ github.event.inputs.logicapp }}/workflow.json \
            --parameters logic-apps/${{ github.event.inputs.logicapp }}/parameters/${{ github.event.inputs.environment }}.parameters.json
